package database;

/**
 * Created by didii on 3/3/15.
 */
public enum ItemFamily {
    NAME, CONTENT_URL, DATE_CREATED, TITLE, SHORT_TITLE, KEYWORDS, DEPARTMENT, CATEGORY,
    COLLECTION_REFERENCES, AUTHOR, RATINGS, IMPORTANCE, PUBLICATION_ID, LANGUAGE, TFIDF,
    CONTENT
}
